name: ViaVersion
main: us.myles.ViaVersion.ViaVersionPlugin
authors: [Clumsy]
version: 3.2.2-SNAPSHOT
description: Allow newer clients to join older server versions.
load: postworld
api-version: 1.13
loadbefore: [ProtocolLib, ProxyPipe, SpigotLib, SkinRestorer]
softdepend: [ProtocolSupport, PacketListenerApi]
commands:
  viaversion:
    description: Shows ViaVersion Version and more.
    aliases: [viaver, vvbukkit]